### ISSUE TITLE
Error in if (scen@solver$import_format == "gdx")

### ISSUE THREAD

**Issue by awanyulianto** [energyRt/energyRt#29]
How to fix this Error in if (scen@solver$import_format == "gdx")?

**Comment by olugovoy** [comment]
"scen@solver$import_format" is not mature option yet, but should work.
Please check the statement, should be "=" not "==", e.g. scen@solver$import_format = "gdx"
Also, there are some issues with newer version of R and "gdxrrw". If your GAMS version is not the latest one, then gdxrrw library will not work. A workaround would be to install newer version of GAMS to use its gdx library, but solving with the older version.
The steps:
1. Install newer GAMS version, load "gdxrrw" and connect the newer GAMS using "igdx" function.
2. In the solver options, add command line to the GAMS version that will be used to solve the model:
 list(
  lang = "GAMS",
  export_format = "gdx",
  import_format = "gdx",
  # inc3 = gams_options_txt,
  cmdline = 'C:/PATH_TO_OLD_GAMS/gams.exe energyRt.gms', # change to path to GAMS on your system
  # solver = "cbc",
  solver = "cplex"
)
