### ISSUE TITLE
Error in get(data(list = maps[i])) : object 'utopia_island' not found

### ISSUE THREAD

**Issue by charliemsl** [energyRt/energyRt#38]
Hi guys, thanks for your brilliant work on this model. Trying to load the MWE but coming up against this error message when running the 'available options' section under 'utopia map'.

Also the packages rgeos, rgdal and maptools are no longer being maintained. could sf and terra be used instead?

**Comment by abooda1981** [comment]
Hi, I just wanted to second this. This seems like an extremely cool project, but the vignette seems to be missing some pieces; I don't think get(data(maps[i])) is supposed to work given the preceding lines.

**Comment by olugovoy** [comment]
Hi there!
There were a lot of changes in the package recently, the documentation is lagging. But I will update the MWE and push it on the [@dev](https://github.com/energyRt/energyRt/tree/dev) branch in ~2-3 days from now.

**Comment by abooda1981** [comment]
Hello again and thanks! Definitely looking forward to the update. May I suggest though that the problem which was encountered by myself and someone else earlier could be resolved by converting the object "gis" in your vignette here: https://rdrr.io/github/energyRt/energyRt/f/drafts/utopia.Rmd
from a simple features object to an SFC polygon. Specifically, while this line does not work:
`plot(gis)`
This one does: 
`plot(st_geometry(gis))`

**Comment by olugovoy** [comment]
Hi there, 
This version of the testing-model should work :
https://github.com/energyRt/energyRt/blob/dev/drafts/utopia_20240301.Rmd
but with @dev version of the package
remotes::install_github("energyRt/energyRt", ref = "dev")
Pls let me know if any issues.

**Comment by olugovoy** [comment]
closing, since it was solved
