### ISSUE TITLE
Error in .check_sets(scen) :    Unknown sets

### ISSUE THREAD

**Issue by AboodaA** [energyRt/energyRt#40]
Hello. I followed the instructions and the order of procedures which you list in the instruction R Markup file. I received the "unknown sets" error however. I was able to overcome the first hurdle by using option (en.debug = TRUE) before running the scenario but I then exit quickly with the status code 2. 

These are the unknown sets: 

            name    set  value
          <char> <char> <char>
1:  mTechOneComm   comm    CH4
2:     mTechAOut   comm    CH4
3: mTechAct2AOut   comm    CH4
4: pTechEmisComm   comm    CH4
5: pTechAct2AOut  acomm    CH4
6:    mvTechAOut   comm    CH4

Am I supposed to declare these earlier somewhere in my code before executing the scenario? I cannot find a reference to them in the introduction vignette. 

In case it is important: I used the PYOMO solver; I am running Ubuntu 20.04 and R version 4.3.2.

**Comment by olugovoy** [comment]
Hello, thanks for reporting, and good to know it is solved. If any other issues, please also report the version number and, if possible, a minimal reproducible example with the error.
Also please keep in mind that the most current version is on "dev" branch, we will merge in with the "master" quite soon.
